---
apiVersion: v1
kind: Service
metadata:
  name: vault-dev
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8200
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: vault-dev-1
  labels:
    kubernetes.io/service-name: vault-dev
addressType: IPv4
ports:
  - protocol: TCP
    port: 8200
endpoints:
  - addresses:
    - "192.168.1.150"
